
name: "Create a release"

description: "Creates a release based on CHANGELOG.md"
inputs:
  github-token:
    description: "GitHub token of a user with permission to create a release"
    required: true

runs:
  using: "composite"

  steps:
    - name: "Determine max version"
      id: get_max_version
      uses: "./.github/actions/get-max-version"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.get_max_version.outputs.max-version }}
        release_name: ${{ steps.get_max_version.outputs.max-version }}
        draft: false
        prerelease: false
