apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      serviceAccountName: quarkus-qs-kube-sa
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
      - name: java-app-container
        image: {{ .Values.region }}-docker.pkg.dev/{{ .Values.project_id }}/quickstart-docker-repo/quickstart-image:tag6
        ports:
        - containerPort: 8080
        env:
          - name: PROJECT_ID
            value: {{ .Values.project_id }}
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: 8080
          initialDelaySeconds: 3
