apiVersion: v1
kind: ServiceAccount
metadata:
  name: quarkus-qs-kube-sa
  annotations:
    "iam.gke.io/gcp-service-account": quickstart-accessspanner@{{ .Values.project_id }}}.iam.gserviceaccount.com