
name: "Release"

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - "**"

jobs:
  release:
    name: "Release"
    permissions:
      contents: write
    runs-on: "ubuntu-latest"

    steps:
      - name: "Create release"
        uses: "../actions/create-release-on-tag.yaml"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"